const products = [
    {
        id: 0,
        name: "GREY MINI DRESS PARIS ",
        price: 39.90,
        desc: "Grey mini dress for all occasions",
        image:"../images/grey.jpg",
        countInstock: 6,
    },
    {
        id: 1,
        name: "BLACK MINI DRESS PARIS ",
        price: 39.00,
        desc: "Grey mini dress for all occasions",
        image:"../images/black.jpg",
        image2:"../images/grey.jpg",
        countInstock: 3,
    },
    {
        id: 2,
        name: "ROSE ROXANE ",
        price: 19.90,
        desc: "Grey mini dress for all occasions",
        image:"../images/rose.jpg",
        countInstock: 17,
    },
    {
        id: 2,
        name: "ROSE ROXANE ",
        price: 19.90,
        desc: "Grey mini dress for all occasions",
        image:"../images/rose.jpg",
        countInstock: 17,
    },
    {
        id: 2,
        name: "ROSE ROXANE ",
        price: 19.90,
        desc: "Grey mini dress for all occasions",
        image:"../images/rose.jpg",
        countInstock: 17,
    },
    {
        id: 0,
        name: "GREY MINI DRESS PARIS ",
        price: 39.90,
        desc: "Grey mini dress for all occasions",
        image:"../images/grey.jpg",
        countInstock: 6,
    },
    {
        id: 1,
        name: "BLACK MINI DRESS PARIS ",
        price: 39.00,
        desc: "Grey mini dress for all occasions",
        image:"../images/black.jpg",
        image2:"../images/grey.jpg",
        countInstock: 3,
    },
    {
        id: 2,
        name: "ROSE ROXANE ",
        price: 19.90,
        desc: "Grey mini dress for all occasions",
        image:"../images/rose.jpg",
        countInstock: 17,
    },
    {
        id: 2,
        name: "ROSE ROXANE ",
        price: 19.90,
        desc: "Grey mini dress for all occasions",
        image:"../images/rose.jpg",
        countInstock: 17,
    },
    {
        id: 2,
        name: "ROSE ROXANE ",
        price: 19.90,
        desc: "Grey mini dress for all occasions",
        image:"../images/rose.jpg",
        countInstock: 17,
    }
];

exports.products = products;